version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - './data/mongodb:/data/db'
      - './log/mongodb:/var/log/mongodb'
      - './conf:/etc/mongo'
    environment:
      TZ: 'Asia/Shanghai'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
